config/routes.rb
Rails.application.routes.draw do
  resources :places do
    post :send_me, on: :member
  end

  resources :professionals do
    get :profile, on: :collection
    post :save_profile, on: :collection
    put :save_profile, on: :collection
    patch :save_profile, on: :collection
    post :send_me, on: :member
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'redirect#redirect', as: :authenticated_root
    end
    
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'redirect', to: 'redirect#redirect', as: 'redirect'

  root to: 'devise/sessions#new'
end

app/models/professional.rb
class Professional < ApplicationRecord
  belongs_to :user

  accepts_nested_attributes_for :user

  scope :actived, -> { where(active: true) }
  scope :with_city, ->(city) { where('city ILIKE ?', "%#{city}%") }
  scope :with_state, ->(state) { where('state ILIKE ?', "%#{state}%") }
  scope :with_occupation, ->(occupation) { where('occupation ILIKE ?', "%#{occupation}%") }
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show, :send_me]
  before_action :authorization_base

  has_scope :with_city
  has_scope :with_state
  has_scope :with_occupation

  # GET /professionals
  def index
    @pagy, @professionals = pagy(apply_scopes(policy_scope(Professional)), items: 10)
  end

  # GET /professionals/1
  def show
  end

  # GET /professionals/profile
  def profile
    @professional = Professional.find_by_user_id(current_user.id) || Professional.new(user: current_user)
  end

  # POST/PUT/PATCH /professionals/save_profile
  def save_profile
    @professional = Professional.find_by_user_id(current_user.id) || Professional.new(user: current_user)
    @professional.assign_attributes(permitted_attributes(@professional))
    if @professional.save
      redirect_to profile_professionals_path, notice: 'Perfil atualizado com sucesso!'
    else
      render :profile
    end
  end

  # POST /professionals/1/send_me
  def send_me
    ProfessionalMailer.with(user: current_user, professional: @professional).send_me.deliver_now
    redirect_to @professional, notice: 'E-mail enviado com sucesso!'
  end

  private
  
  def authorization_base
    authorize Professional
  end

  def set_professional
    @professional ||= Professional.find(params[:id])
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    <%= action %>
  </div>
  <%= simple_form_for @professional, url: save_profile_professionals_path do |f| %>
    <div class="card-body">
      <%= f.simple_fields_for :user do |u| %>
        <%= u.input :name, label: 'Nome' %>
        <%= u.input :email %>
      <% end %>

      <%= f.input :occupation %>
      <%= f.input :company %>
      <%= f.input :linkedin %>
      <%= f.input :facebook %>
      <%= f.input :twitter %>
      <%= f.input :cellphone %>
      <%= f.input :phone %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :active %>

      <hr />
      <%= f.submit "Salvar", class: 'btn btn-primary btn-sm' %>
    </div>
  <% end %>
</div

app/views/professionals/_form_filter.html.erb
<%= form_tag( '' , method: :get, class: 'form-row' ) do |f| %>
  <div class="col-4">
    <%= text_field_tag :with_city, params[:with_city], class: 'form-control', placeholder: 'Cidade' %>
  </div>
  <div class="col-4">
    <%= text_field_tag :with_state, params[:with_state], class: 'form-control', placeholder: 'Estado' %>
  </div>
  <div class="col-4">
    <%= text_field_tag :with_occupation, params[:with_occupation], class: 'form-control', placeholder: 'Profissão' %>
  </div>
  <div class="col-12 mt-2 mb-2">
    <button type="submit" class="btn btn-primary btn-sm">Pesquisar</button>
  </div>
<% end %>

app/views/professionals/index.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    Profissionais
  </div>
  <div class="card-body">
    <%= render 'form_filter' %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Cidade</th>
            <th>Estado</th>
            <th>Profissão</th>
            <th>Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @professionals.each do |professional| %>
            <tr>
              <td><%= professional.user.name %></td>
              <td><%= professional.city %></td>
              <td><%= professional.state %></td>
              <td><%= professional.occupation %></td>
              <td>
                <div class="btn-group">
                  <%= link_to 'Exibir', professional, class: 'btn btn-warning btn-sm' if policy(Place).show? %>
                </div>
              </td>
            </tr>
          <% end %>
          <% if @professionals.empty? %>
            <tr>
              <td colspan=2>Não foram encontrados profissionais.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr />
  </div>
</div>

app/views/professionals/profile.html.erb
<%= render 'form', action: 'Meu Perfil' %>

app/views/professionals/show.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    Profissional
  </div>
  <div class="card-body">
    <%= link_to  "Enviar para meu e-mail", send_me_professional_path(@professional), method: :post, class: 'btn btn-info btn-sm float-right mb-2' if policy(Professional).send_me? %>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Nome</th>
          <td><%= @professional.user.name %></td>
        </tr>
        <tr>
          <th>E-mail</th>
          <td><%= @professional.user.email %></td>
        </tr>
        <tr>
          <th>Profissão</th>
          <td><%= @professional.occupation %></td>
        </tr>
        <tr>
          <th>Empresa</th>
          <td><%= @professional.company %></td>
        </tr>
        <tr>
          <th>Linkedin</th>
          <td><%= @professional.linkedin %></td>
        </tr>
        <tr>
          <th>Facebook</th>
          <td><%= @professional.facebook %></td>
        </tr>
        <tr>
          <th>Twitter</th>
          <td><%= @professional.twitter %></td>
        </tr>
        <tr>
          <th>Celular</th>
          <td><%= @professional.cellphone %></td>
        </tr>
        <tr>
          <th>Telefone</th>
          <td><%= @professional.phone %></td>
        </tr>
        <tr>
          <th>Cidade</th>
          <td><%= @professional.city %></td>
        </tr>
        <tr>
          <th>Estado</th>
          <td><%= @professional.state %></td>
        </tr>
      </table>
    </div>
  </div>
</div>