config/routes.rb
Rails.application.routes.draw do
  resources :places do
    post :send_me, on: :member
  end

  resources :professionals do
    get :profile, on: :collection
    post :save_profile, on: :collection
    put :save_profile, on: :collection
    patch :save_profile, on: :collection
    post :send_me, on: :member
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'redirect#redirect', as: :authenticated_root
    end
    
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'redirect', to: 'redirect#redirect', as: 'redirect'

  root to: 'devise/sessions#new'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :place_schedules
  
  has_many_attached :photos

  accepts_nested_attributes_for :place_schedules, allow_destroy: true
  accepts_nested_attributes_for :photos_attachments, allow_destroy: true

  enum description: {living_room: 1, meeting_room: 2, video_conference_room: 3, lounge: 4}

  validates :description, presence: true
  validates :photos, presence: true, blob: { content_type: :image }

  scope :with_city, ->(city) { where('city ILIKE ?', "%#{city}%") }
  scope :with_state, ->(state) { where('state ILIKE ?', "%#{state}%") }
  scope :with_occupation, ->(occupation) { where('occupation ILIKE ?', "%#{occupation}%") }
  scope :min_price, ->(price) { where('price_per_hour >= ?', price) }
  scope :max_price, ->(price) { where('price_per_hour <= ?', price) }
  scope :min_date, ->(date) { where('end_date >= ?', date) }
  scope :max_date, ->(date) { where('start_date <= ?', date) }
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy, :send_me]
  before_action :authorization_base
  
  has_scope :with_city
  has_scope :with_state
  has_scope :with_occupation
  has_scope :min_price
  has_scope :max_price
  has_scope :min_date
  has_scope :max_date

  # GET /places
  def index
    @pagy, @places = pagy(apply_scopes(policy_scope(Place)), items: 10)
  end

  # GET /places/1
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = Place.new(permitted_attributes(Place))
    if @place.save
      redirect_to @place, notice: 'Place foi criado com sucesso!.'
    else
      render :new
    end
  end

  # PATCH/PUT /places/1/edit
  def update
    if @place.update(permitted_attributes(@place))
      redirect_to @place, notice: 'Place foi criado com sucesso!.'
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, notice: 'Place foi removido com sucesso!.'
  end

  # POST /places/1/send_me
  def send_me
    PlaceMailer.with(user: current_user, place: @place).send_me.deliver_now
    redirect_to @place, notice: 'E-mail enviado com sucesso!'
  end

  private
  
  def authorization_base
    authorize Place
  end

  def set_place
    @place ||= Place.find(params[:id])
  end
end

app/views/places/_form.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    <%= action %> lugar
  </div>
  <%= simple_nested_form_for @place do |f| %>
    <div class="card-body">
      <%= f.input :description, collection: Place.descriptions.map{ |description| [t(description.first), description.first] } %>
      <%= f.input :street %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :number_of_tables %>
      <%= f.input :number_of_chairs %>
      <%= f.input :price_per_hour %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>

      <%= f.input :photos, input_html: { multiple: true }, hint: 'Selecione vários arquivos, para envio de mais de uma foto.' %>
      <% if @place.photos.present? %>
        <hr />
        <h5 class="card-title">Imagens</h5>
        <%= f.simple_fields_for :photos_attachments do |photo_form| %>
          <%= link_to photo_form.object.blob.filename.to_s, url_for(photo_form.object), target: '_blank' %>
          <%= photo_form.link_to_remove class: 'btn btn-danger btn-sm' do %>
            X
          <% end %>
          <br />
        <% end %>
        <hr />
      <% end %>

      <h5 class="card-title">Horários Disponíveis</h5>
      <%= f.simple_fields_for :place_schedules do |place_schedule_form| %>
        <div class="row">
          <div class="col-sm-5">
            <%= place_schedule_form.label :weekdays %>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <%= place_schedule_form.input :sunday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :monday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :tuesday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :wednesday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :thursday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :friday, wrapper: :boolean_btn %>
              <%= place_schedule_form.input :saturday, wrapper: :boolean_btn %>
            </div>
          </div>
          <div class="col-sm-3">
            <%= place_schedule_form.input :start %>
          </div>
          <div class="col-sm-3">
            <%= place_schedule_form.input :end %>
          </div>
          <div class="col-sm-1 d-flex justify-content-end align-items-center">
            <%= place_schedule_form.link_to_remove class: 'btn btn-danger btn-sm' do %>
              X
            <% end %>
          </div>
        </div>
      <% end %>
      <%= f.link_to_add 'Adicionar horário', :place_schedules, class: 'btn btn-primary btn-sm float-right' %>
      <div class="clearfix"></div>
      <hr />
      <%= f.submit "#{action} lugar", class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Voltar', places_path, class: 'btn btn-secondary btn-sm' %>
    </div>
  <% end %>
</div

app/views/places/_form_filter.html.erb
<%= form_tag( '' , method: :get, class: 'form-row' ) do |f| %>
  <div class="col-4">
    <%= text_field_tag :with_city, params[:with_city], class: 'form-control', placeholder: 'Cidade' %>
  </div>
  <div class="col-4">
    <%= text_field_tag :with_state, params[:with_state], class: 'form-control', placeholder: 'Estado' %>
  </div>
  <div class="col-4">
    <%= text_field_tag :with_occupation, params[:with_occupation], class: 'form-control', placeholder: 'Profissão' %>
  </div>
  <div class="col-3 mt-2">
    <%= text_field_tag :min_price, params[:min_price], class: 'form-control', placeholder: 'Preço Mínimo' %>
  </div>
  <div class="col-3 mt-2">
    <%= text_field_tag :max_price, params[:max_price], class: 'form-control', placeholder: 'Preço Máximo' %>
  </div>
  <div class="col-3 mt-2">
    <%= text_field_tag :min_date, params[:min_date], class: 'form-control', placeholder: 'Data Mínima' %>
  </div>
  <div class="col-3 mt-2">
    <%= text_field_tag :max_date, params[:max_date], class: 'form-control', placeholder: 'Data Máxima' %>
  </div>
  <div class="col-12 mt-2 mb-2">
    <button type="submit" class="btn btn-primary btn-sm">Pesquisar</button>
  </div>
<% end %>

app/views/places/edit.html.erb
<%= render 'form', action: 'Atualizar' %>

app/views/places/index.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    Lugares
  </div>
  <div class="card-body">
    <%= render 'form_filter' %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Descricão</th>
            <th>Preço/h</th>
            <th>A partir de:</th>
            <th>Até:</th>
            <th>Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><%= t place.description %></td>
              <td><%= place.price_per_hour %></td>
              <td><%= l place.start_date %></td>
              <td><%= l place.end_date %></td>
              <td>
                <div class="btn-group">
                  <%= link_to 'Exibir', place, class: 'btn btn-warning btn-sm' if policy(Place).show? %>
                  <%= link_to 'Editar', edit_place_path(place), class: 'btn btn-info btn-sm' if policy(Place).edit? %>
                  <%= link_to 'Excluir', place, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Você tem certeza?' }  if policy(Place).destroy? %>
                </div>
              </td>
            </tr>
          <% end %>
          <% if @places.empty? %>
            <tr>
              <td colspan=2>Não há lugares cadastrados.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr />

    <%= link_to 'Adicionar Lugar', new_place_path, class: 'btn btn-primary btn-sm' if policy(Place).new? %>
  </div>
</div>

app/views/places/new.html.erb
<%= render 'form', action: 'Adicionar' %>

app/views/places/show.html.erb
<div class="card">
  <div class="card-header text-white bg-dark">
    Lugar
  </div>
  <div class="card-body">
    <%= link_to  "Enviar para meu e-mail", send_me_place_path(@place), method: :post, class: 'btn btn-info btn-sm float-right mb-2' if policy(Place).send_me? %>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Descrição</th>
          <td><%= t @place.description %></td>
        </tr>
        <tr>
          <th>Logradouro</th>
          <td><%= @place.street %></td>
        </tr>
        <tr>
          <th>Cidade</th>
          <td><%= @place.city %></td>
        </tr>
        <tr>
          <th>Estado</th>
          <td><%= @place.state %></td>
        </tr>
        <tr>
          <th>Número de Mesas</th>
          <td><%= @place.number_of_tables %></td>
        </tr>
        <tr>
          <th>Número de Cadeiras</th>
          <td><%= @place.number_of_chairs %></td>
        </tr>
        <tr>
          <th>Preço por Hora</th>
          <td><%= @place.price_per_hour %></td>
        </tr>
        <tr>
          <th>Data Inicial</th>
          <td><%= l @place.start_date %></td>
        </tr>
        <tr>
          <th>Data Final</th>
          <td><%= l @place.end_date %></td>
        </tr>
      </table>
    </div>
    <h5 class="card-title">Horários</h5>
    <div class="table-responsive">
      <table class='table'>
        <thead>
          <th nowrap>
            <span data-toggle="tooltip" title="Dias da Semana">Dias da Semana</span>
          </th>
          <th nowrap>
            <span data-toggle="tooltip" title="Início">Início</span>
          </th>
          <th nowrap>
            <span data-toggle="tooltip" title="Término">Término</span>
          </th>
        <thead>
        <tbody>
          <% @place.place_schedules.each do |schedule| %>
            <tr>
              <td nowrap>
                <% if schedule.sunday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:sunday) %></span>
                <% end %>
                <% if schedule.monday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:monday) %></span>
                <% end %>
                <% if schedule.tuesday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:tuesday) %></span>
                <% end %>
                <% if schedule.wednesday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:wednesday) %></span>
                <% end %>
                <% if schedule.thursday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:thursday) %></span>
                <% end %>
                <% if schedule.friday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:friday) %></span>
                <% end %>
                <% if schedule.saturday? %>
                  <span class='badge badge-pill badge-dark'><%= PlaceSchedule.human_attribute_name(:saturday) %></span>
                <% end %>
              </td>
              <td nowrap><%= l schedule.start, format: '%H:%M' %></td>
              <td nowrap><%= l schedule.end, format: '%H:%M' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>