config/routes.rb
Rails.application.routes.draw do
  resources :places do
    post :send_me, on: :member
  end

  resources :professionals do
    get :profile, on: :collection
    post :save_profile, on: :collection
    put :save_profile, on: :collection
    patch :save_profile, on: :collection
    post :send_me, on: :member
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'redirect#redirect', as: :authenticated_root
    end
    
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'redirect', to: 'redirect#redirect', as: 'redirect'

  root to: 'devise/sessions#new'
end

app/views/layouts/_sidebar.html.erb
<div class="list-group mb-4">
  <%= active_link_to "Meu Perfil", profile_professionals_path, class: 'list-group-item list-group-item-action' if policy(Professional).profile? %>
  <%= active_link_to "Lugares", places_path, class: 'list-group-item list-group-item-action' if policy(Place).index? %>
  <%= active_link_to "Profissionais", professionals_path, class: 'list-group-item list-group-item-action' if policy(Professional).index? %>

  <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'list-group-item list-group-item-action', data: { confirm: 'Você tem certeza?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemMesaLivre</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Tem Mesa Livre</a>
    </nav>
    <div class="container-fluid mt-4">
      <div class="row">
        <div class="col-md-4">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="col-md-8">
          <% if notice.present? %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% end %>

          <% if alert.present? %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemMesaLivre</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="tml-login">
    <div class="card">
      <div class="card-body">
        <% if notice.present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% end %>

        <% if alert.present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <%= yield :javascript %>
  </body>
</html>